#!/bin/bash
if [ $# == 1 ]
then
git config --global user.email santamaksimova11@inbox.lv
git add .
#git commit -m "20171011"
git commit -m $1
git push origin master
fi
gut config --global user.email santamaksimova11@inbox.lv
git add .
#git commit -m "20171018"
git commit -m $1
git push origin master
fi
